"""AI-generated migration narrative — presentation-layer prose, nothing more.

Distinct from the deterministic per-instance `reason` (`ComputePlan.reason`,
`decisions.json`): this is a short, human-readable *paragraph* summarizing
the migration for the executive report. It is generated by Claude only when
the plan itself was actually classified/sized by the Anthropic provider
(`plan.provider_used == "anthropic"`) — narrative generation piggybacks on
that same "AI is on" signal rather than making an independent, possibly
inconsistent choice about whether to call out to the API.

This module does not make decisions. It runs strictly downstream of the
immutable `MigrationPlan`, reads facts already computed (assessment,
confidence, cost), and never influences the plan or any rendered IaC — the
same read-only relationship the executive report itself has to the plan.

When AI wasn't used (the default, and the common case with no
`ANTHROPIC_API_KEY`), a deterministic templated paragraph is produced from
the identical facts instead. The report always renders a narrative section;
it is always clearly labeled which mode produced it, and a paragraph is never
mislabeled as AI-written when it wasn't. Any API error falls back to the
deterministic paragraph rather than breaking report generation.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional

from .assessment.models import InfrastructureAssessment
from .confidence import PlanConfidence
from .models import MigrationPlan

DEFAULT_MODEL = "claude-opus-4-8"


@dataclass
class Narrative:
    text: str
    source: str  # "ai" | "deterministic"
    model: Optional[str] = None


def _facts(plan: MigrationPlan, assessment: InfrastructureAssessment, confidence: PlanConfidence) -> str:
    total_cost = plan.total_estimated_monthly_cost_usd
    right_sized = sum(1 for c in plan.compute if c.right_sized)
    tiers = sorted({c.tier.value for c in plan.compute})
    low_conf = confidence.low_confidence()
    return (
        f"{plan.vm_count} workload(s) migrating from {plan.source_platform} to "
        f"{plan.target.upper()} ({plan.region}); tiers present: {', '.join(tiers) or 'none'}. "
        f"Estimated cost: ${total_cost:,.2f}/month ({plan.pricing_source} pricing). "
        f"{right_sized} of {plan.vm_count} instances were right-sized to observed utilization. "
        f"Migration readiness: {assessment.readiness.score}/100 "
        f"({assessment.readiness.band.replace('-', ' ')}) — {assessment.readiness.rationale} "
        f"Translation confidence: {confidence.overall * 100:.0f}% ({confidence.level}); "
        f"{len(low_conf)} workload(s) below the review threshold."
    )


def _deterministic_narrative(
    plan: MigrationPlan, assessment: InfrastructureAssessment, confidence: PlanConfidence
) -> str:
    """A templated paragraph from the same facts an AI narrative would use —
    no LLM, always available, always accurate to the numbers above it."""
    total_cost = plan.total_estimated_monthly_cost_usd
    right_sized = sum(1 for c in plan.compute if c.right_sized)
    tiers = sorted({c.tier.value for c in plan.compute})
    low_conf = confidence.low_confidence()
    tier_clause = f"spanning the {', '.join(tiers)} tier(s)" if tiers else ""
    review_clause = (
        f"{len(low_conf)} workload(s) — "
        + ", ".join(w.vm_name for w in low_conf[:5])
        + ("…" if len(low_conf) > 5 else "")
        + " — warrant manual review before cutover."
        if low_conf else "No workloads fell below the confidence threshold for review."
    )
    return (
        f"This migration moves {plan.vm_count} workload(s) from {plan.source_platform} to "
        f"{plan.target.upper()} ({plan.region}), {tier_clause}. Estimated monthly cost is "
        f"${total_cost:,.2f}, with {right_sized} of {plan.vm_count} instances right-sized to "
        f"observed utilization rather than raw allocation. The estate's migration readiness "
        f"scores {assessment.readiness.score}/100 ({assessment.readiness.band.replace('-', ' ')}), "
        f"and the generated plan carries {confidence.overall * 100:.0f}% average translation "
        f"confidence ({confidence.level}). {review_clause}"
    )


def _ai_narrative(
    plan: MigrationPlan, assessment: InfrastructureAssessment, confidence: PlanConfidence
) -> Narrative:
    import anthropic

    client = anthropic.Anthropic()
    model = os.getenv("IACTRANSLATE_ANTHROPIC_MODEL", DEFAULT_MODEL)
    findings = "; ".join(f.title for f in assessment.findings[:5]) or "none"
    msg = client.messages.create(
        model=model,
        max_tokens=400,
        system=(
            "You write concise, professional migration-summary paragraphs for a cloud "
            "migration report read by both engineers and executives. Use only the facts "
            "given below; never invent numbers, risks, or recommendations that aren't "
            "present in the input. Write 2-3 short paragraphs, plain prose — no headers, "
            "no bullet points, no markdown formatting."
        ),
        messages=[{
            "role": "user",
            "content": f"Facts: {_facts(plan, assessment, confidence)}\nTop findings: {findings}",
        }],
    )
    text = "".join(b.text for b in msg.content if getattr(b, "type", None) == "text").strip()
    if not text:
        raise ValueError("empty response from Anthropic")
    return Narrative(text=text, source="ai", model=model)


def generate_narrative(
    plan: MigrationPlan, assessment: InfrastructureAssessment, confidence: PlanConfidence
) -> Narrative:
    """Produce the migration-summary paragraph for the executive report.

    AI only runs when the plan was actually classified/sized by the
    Anthropic provider AND a key is present — matching exactly the condition
    under which `plan.provider_used == "anthropic"` could be true. Any
    failure (network, API, empty response) falls back to the deterministic
    paragraph; report generation never breaks because of this.
    """
    if plan.provider_used == "anthropic" and os.getenv("ANTHROPIC_API_KEY"):
        try:
            return _ai_narrative(plan, assessment, confidence)
        except Exception:
            pass
    return Narrative(text=_deterministic_narrative(plan, assessment, confidence), source="deterministic")
