"""Parsing a *structurally realistic* RVTools workbook (ADR 0035).

The committed `rvtools_sample.xlsx` has 3 sheets and 10 columns. A real export
has 14+ sheets and ~50 columns on `vInfo`, and Azure Migrate documents files of
up to 20,000 servers. Testing only against the tidy fixture meant the parser
had never seen the shape it will actually be handed.

The fixture here is generated by `scripts/make_rvtools_fixture.py` using the
sheet and column names from Microsoft's RVTools import spec.
"""
from __future__ import annotations

import pytest

from iactranslate.agents import build_migration_plan
from iactranslate.agents.rightsizing import os_substitution_note
from iactranslate.normalize import normalize
from iactranslate.sources import resolve_source
from iactranslate.targets import get_target, list_targets

FIXTURE = "tests/fixtures/rvtools_realistic.xlsx"


@pytest.fixture(scope="module")
def realistic_vms():
    src = resolve_source(FIXTURE, "auto")
    return src, normalize(src.parse(FIXTURE))


def test_detects_rvtools_among_fourteen_sheets(realistic_vms):
    src, vms = realistic_vms
    assert src.name == "vmware"
    assert len(vms) == 25


def test_reads_only_the_sheets_it_uses():
    """A real export carries vHost/vDatastore/vSnapshot/dvPort and more.
    Loading them costs time and memory for data nothing reads."""
    from iactranslate.sources.vmware.rvtools import _read_sheets

    sheets = _read_sheets(FIXTURE)
    assert set(sheets) == {"vinfo", "vdisk", "vnetwork"}


def test_multi_disk_vms_aggregate_from_the_vdisk_sheet(realistic_vms):
    """Real vDisk has one row per disk; a 5-disk VM must not become a 1-disk VM."""
    _, vms = realistic_vms
    multi = [vm for vm in vms if len(vm.disks_gib) > 1]
    assert multi, "fixture should contain multi-disk machines"
    for vm in multi:
        assert vm.total_disk_gib == pytest.approx(sum(vm.disks_gib))


def test_real_rvtools_os_strings_resolve_to_images(realistic_vms):
    """RVTools reports 'Ubuntu Linux (64-bit)', not 'Ubuntu 22.04'."""
    _, vms = realistic_vms
    target = get_target("aws")
    for vm in vms:
        key = target.image_key(vm.os)
        assert key and key != "", f"{vm.os!r} resolved to nothing"


def test_powered_off_machines_are_kept_not_dropped(realistic_vms):
    """~12% of a real estate is powered off. They still cost money in the
    plan and must be visible, not silently discarded."""
    _, vms = realistic_vms
    assert any((vm.power_state or "").lower() == "poweredoff" for vm in vms)


@pytest.mark.parametrize("target_name", list_targets())
def test_realistic_estate_plans_cleanly_for_every_cloud(realistic_vms, target_name):
    _, vms = realistic_vms
    plan = build_migration_plan(vms, project_name="realistic", target=get_target(target_name))
    assert plan.vm_count == len(vms)
    labels = [c.resource_name for c in plan.compute]
    assert len(labels) == len(set(labels)), "duplicate Terraform resource label"


# -- OS substitution must be stated, never silent ---------------------------


def test_end_of_life_windows_substitution_is_disclosed():
    """Windows Server 2012 R2 is EOL and the clouds no longer publish a base
    image, so a plan must fall forward — but the reviewer has to be told, since
    an app certified against 2012 R2 may not run on 2022."""
    note = os_substitution_note("Microsoft Windows Server 2012 R2 (64-bit)", "windows-2022")
    assert note and "2012" in note and "windows-2022" in note
    assert "compatibility" in note.lower()


def test_matching_versions_are_not_flagged():
    """Crying wolf on every machine would make the real warnings invisible."""
    for os_string, key in [
        ("Microsoft Windows Server 2019 (64-bit)", "windows-2019"),
        ("Red Hat Enterprise Linux 8 (64-bit)", "rhel-8"),
        ("CentOS 7 (64-bit)", "centos-7"),
    ]:
        assert os_substitution_note(os_string, key) is None


def test_architecture_suffix_is_not_read_as_a_version():
    """Every RVTools OS string ends in '(64-bit)'. Left in, the '64' reads as a
    version and every Ubuntu machine gets reported as a substitution."""
    assert os_substitution_note("Ubuntu Linux (64-bit)", "ubuntu-22.04") is None
    assert os_substitution_note("Ubuntu Linux (32-bit)", "ubuntu-22.04") is None
    # A version that really is present still gets compared.
    assert os_substitution_note("Ubuntu Linux 20.04 (64-bit)", "ubuntu-22.04") is not None


@pytest.mark.parametrize("target_name", list_targets())
def test_rhel_8_is_not_silently_upgraded_to_rhel_9(target_name):
    """A certified RHEL 8 estate must not become RHEL 9 because that is the
    newest image we happen to stock."""
    target = get_target(target_name)
    assert target.image_key("Red Hat Enterprise Linux 8 (64-bit)") == "rhel-8"
    assert target.image_key("Red Hat Enterprise Linux 9 (64-bit)") == "rhel-9"


def test_substituted_os_appears_in_the_decision_reason():
    """The note must reach `decisions.json` and the report, not just exist."""
    vms = normalize([{
        "name": "legacy-app-01", "cpus": 4, "memory_value": 16, "memory_unit": "GiB",
        "disk_value": 200, "disk_unit": "GiB",
        "os": "Microsoft Windows Server 2012 R2 (64-bit)",
    }])
    plan = build_migration_plan(vms, project_name="legacy", target=get_target("aws"))
    assert "OS substituted" in plan.compute[0].reason
