"""Bicep renderer — the second renderer (after CloudFormation, ADR 0013) to render
from the Infrastructure Graph rather than the MigrationPlan.

Azure-only: Bicep has no cross-cloud equivalent. Emits two files, the standard
Bicep pattern for "create the resource group, then deploy into it":

- `main.bicep`   — subscription-scope: creates the resource group, calls the module.
- `resources.bicep` — resource-group-scope module: vnet/subnets, NSGs (from the
  graph's enriched `ingress` attribute), NICs, public IPs, and VMs (from
  `image_key`/`root_volume_gib` attributes, resolved via `target.image_reference`,
  the same Marketplace publisher/offer/sku table the Terraform and Pulumi
  renderers already use — Azure has no Terraform-`data`-source equivalent to
  invent around, unlike AWS AMIs).

Deterministic string generation — no AI. There is no local Bicep compiler
available to validate against (unlike `tofu validate` for Terraform or
`cfn-lint` for CloudFormation); tests assert structural properties (every
`resource`/`param`/`module` line matches Bicep grammar shape, brace balance,
one `resource` block per graph node) rather than a real compile.
"""
from __future__ import annotations

from typing import Dict, List

from ..graph import EdgeKind, InfrastructureGraph, NodeKind, build_graph
from ..models import MigrationPlan, terraform_safe_name
from ..targets.base import Target


class RendererNotSupportedError(ValueError):
    pass


def _id(name: str) -> str:
    """A valid Bicep identifier (camelCase, alnum + underscore, starts with a letter)."""
    safe = terraform_safe_name(name)
    parts = safe.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _str(s: str) -> str:
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def _nsg_rule(rule: dict, priority: int) -> List[str]:
    port = f"{rule['from_port']}" if rule["from_port"] == rule["to_port"] else f"{rule['from_port']}-{rule['to_port']}"
    cidr = rule["cidr_blocks"][0] if rule["cidr_blocks"] else "*"
    return [
        "      {",
        f"        name: {_str('rule' + str(priority))}",
        "        properties: {",
        f"          priority: {priority}",
        "          direction: 'Inbound'",
        "          access: 'Allow'",
        f"          protocol: {_str(rule['protocol'].capitalize())}",
        "          sourcePortRange: '*'",
        f"          destinationPortRange: {_str(port)}",
        f"          sourceAddressPrefix: {_str(cidr)}",
        "          destinationAddressPrefix: '*'",
        "        }",
        "      }",
    ]


def _resources_bicep(graph: InfrastructureGraph, plan: MigrationPlan, target: Target) -> str:
    is_windows = {c.resource_name: c.image_key.startswith("windows") for c in plan.compute}

    lines: List[str] = [
        "// Generated by IaCTranslate — deployed into the resource group by main.bicep.",
        "// Rendered from the Infrastructure Graph (see docs/adr/0010-infrastructure-graph.md).",
        "",
        "param location string",
        "param adminUsername string = 'azureuser'",
        "@secure()",
        "param adminPassword string = ''",
        "param adminSshPublicKey string = ''",
        "",
    ]

    vpc = graph.nodes_of(NodeKind.VPC)[0]
    vnet_id = _id(f"vnet-{plan.project_name}")
    lines += [
        f"resource {vnet_id} 'Microsoft.Network/virtualNetworks@2023-05-01' = {{",
        f"  name: {_str(plan.project_name + '-vnet')}",
        "  location: location",
        "  properties: {",
        f"    addressSpace: {{ addressPrefixes: [{_str(vpc.attributes['cidr'])}] }}",
        "  }",
        "}",
        "",
    ]

    subnet_id_by_node: Dict[str, str] = {}
    for s in graph.nodes_of(NodeKind.SUBNET):
        sid = _id(f"subnet-{s.name}")
        subnet_id_by_node[s.id] = sid
        lines += [
            f"resource {sid} 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' = {{",
            f"  parent: {vnet_id}",
            f"  name: {_str(s.name)}",
            f"  properties: {{ addressPrefix: {_str(s.attributes['cidr'])} }}",
            "}",
            "",
        ]

    sg_id_by_node: Dict[str, str] = {}
    for sg in graph.nodes_of(NodeKind.SECURITY_GROUP):
        gid = _id(f"nsg-{sg.name}")
        sg_id_by_node[sg.id] = gid
        rules: List[str] = []
        for i, rule in enumerate(sg.attributes["ingress"]):
            rules += _nsg_rule(rule, 100 + i * 10)
        lines += [
            f"resource {gid} 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {{",
            f"  name: {_str(sg.name)}",
            "  location: location",
            "  properties: {",
            "    securityRules: [",
            *rules,
            "    ]",
            "  }",
            "}",
            "",
        ]

    backend_pool_ref_by_vm_name: Dict[str, str] = {}
    for lb in graph.nodes_of(NodeKind.LOAD_BALANCER):
        lb_var = _id(f"lb-{lb.name}")
        placed_in = graph.out_edges(lb.id, EdgeKind.PLACED_IN)

        frontend_props: List[str]
        if lb.attributes["internet_facing"]:
            pip_var = _id(f"pip-{lb.name}")
            lines += [
                f"resource {pip_var} 'Microsoft.Network/publicIPAddresses@2023-05-01' = {{",
                f"  name: {_str(lb.name + '-pip')}",
                "  location: location",
                "  sku: { name: 'Standard' }",
                "  properties: { publicIPAllocationMethod: 'Static' }",
                "}",
                "",
            ]
            frontend_props = [f"        properties: {{ publicIPAddress: {{ id: {pip_var}.id }} }}"]
        else:
            # Standard LB doesn't need a subnet per AZ the way an AWS ALB does;
            # one private frontend in the tier's first subnet is sufficient.
            subnet_var = subnet_id_by_node[placed_in[0].target] if placed_in else vnet_id
            frontend_props = [
                "        properties: {",
                f"          subnet: {{ id: {subnet_var}.id }}",
                "          privateIPAllocationMethod: 'Dynamic'",
                "        }",
            ]

        probes = []
        rules = []
        for listener in lb.attributes["listeners"]:
            probe_name = f"probe{listener['listener_port']}"
            rule_name = f"rule{listener['listener_port']}"
            probes.append(
                "      {\n"
                f"        name: {_str(probe_name)}\n"
                "        properties: {\n"
                "          protocol: 'Tcp'\n"
                f"          port: {listener['target_port']}\n"
                "          intervalInSeconds: 15\n"
                "          numberOfProbes: 2\n"
                "        }\n"
                "      }"
            )
            rules.append(
                "      {\n"
                f"        name: {_str(rule_name)}\n"
                "        properties: {\n"
                f"          frontendIPConfiguration: {{ id: {lb_var}.properties.frontendIPConfigurations[0].id }}\n"
                f"          backendAddressPool: {{ id: {lb_var}.properties.backendAddressPools[0].id }}\n"
                f"          probe: {{ id: {lb_var}.properties.probes[{len(probes) - 1}].id }}\n"
                "          protocol: 'Tcp'\n"
                f"          frontendPort: {listener['listener_port']}\n"
                f"          backendPort: {listener['target_port']}\n"
                "        }\n"
                "      }"
            )

        lines += [
            f"resource {lb_var} 'Microsoft.Network/loadBalancers@2023-05-01' = {{",
            f"  name: {_str(lb.name)}",
            "  location: location",
            "  sku: { name: 'Standard' }",
            "  properties: {",
            "    frontendIPConfigurations: [",
            "      {",
            "        name: 'frontend'",
            *frontend_props,
            "      }",
            "    ]",
            "    backendAddressPools: [ { name: 'backendPool' } ]",
            "    probes: [",
            ",\n".join(probes),
            "    ]",
            "    loadBalancingRules: [",
            ",\n".join(rules),
            "    ]",
            "  }",
            "}",
            "",
        ]
        # Azure LB has no NSG property of its own — the backend instances'
        # NICs already carry the tier's NSG (same ingress rules this LB's
        # listeners were derived from), so enforcement is unaffected.
        for e in graph.out_edges(lb.id, EdgeKind.FRONTS):
            target_node = graph.node(e.target)
            if target_node is not None:
                backend_pool_ref_by_vm_name[target_node.name] = f"{lb_var}.properties.backendAddressPools[0].id"

    for c in plan.compute:
        inst = next(n for n in graph.nodes_of(NodeKind.INSTANCE) if n.name == c.vm_name)
        placed_in = graph.out_edges(inst.id, EdgeKind.PLACED_IN)
        secured_by = graph.out_edges(inst.id, EdgeKind.SECURED_BY)
        subnet_ref = subnet_id_by_node[placed_in[0].target] if placed_in else None
        sg_refs = [sg_id_by_node[e.target] for e in secured_by if e.target in sg_id_by_node]
        ref = target.image_reference(inst.attributes["image_key"])
        windows = is_windows[c.resource_name]

        backend_pool_ref = backend_pool_ref_by_vm_name.get(c.vm_name)
        pip_id = None
        # A fronted instance gets its public entry point via the load balancer,
        # not its own public IP — giving it one too would bypass the LB.
        if inst.attributes["subnet_tier"] == "public" and not backend_pool_ref:
            pip_id = _id(f"pip-{c.resource_name}")
            lines += [
                f"resource {pip_id} 'Microsoft.Network/publicIPAddresses@2023-05-01' = {{",
                f"  name: {_str(c.resource_name + '-pip')}",
                "  location: location",
                "  sku: { name: 'Standard' }",
                "  properties: { publicIPAllocationMethod: 'Static' }",
                "}",
                "",
            ]

        nic_id = _id(f"nic-{c.resource_name}")
        ip_config_props = [
            "        properties: {",
            f"          subnet: {{ id: {subnet_ref}.id }}",
            "          privateIPAllocationMethod: 'Dynamic'",
        ]
        if pip_id:
            ip_config_props.append(f"          publicIPAddress: {{ id: {pip_id}.id }}")
        if backend_pool_ref:
            ip_config_props.append(f"          loadBalancerBackendAddressPools: [ {{ id: {backend_pool_ref} }} ]")
        ip_config_props.append("        }")
        nic_body = [
            f"resource {nic_id} 'Microsoft.Network/networkInterfaces@2023-05-01' = {{",
            f"  name: {_str(c.resource_name + '-nic')}",
            "  location: location",
            "  properties: {",
            "    ipConfigurations: [",
            "      {",
            "        name: 'internal'",
            *ip_config_props,
            "      }",
            "    ]",
        ]
        if sg_refs:
            nic_body.append(f"    networkSecurityGroup: {{ id: {sg_refs[0]}.id }}")
        nic_body += ["  }", "}", ""]
        lines += nic_body

        vm_id = _id(f"vm-{c.resource_name}")
        os_profile = (
            [
                "    osProfile: {",
                f"      computerName: {_str(c.resource_name)}",
                "      adminUsername: adminUsername",
                "      adminPassword: adminPassword",
                "    }",
            ]
            if windows
            else [
                "    osProfile: {",
                f"      computerName: {_str(c.resource_name)}",
                "      adminUsername: adminUsername",
                "      linuxConfiguration: {",
                "        disablePasswordAuthentication: true",
                "        ssh: { publicKeys: [ { path: '/home/${adminUsername}/.ssh/authorized_keys'"
                ", keyData: adminSshPublicKey } ] }",
                "      }",
                "    }",
            ]
        )
        lines += [
            f"resource {vm_id} 'Microsoft.Compute/virtualMachines@2023-09-01' = {{",
            f"  name: {_str(c.resource_name)}",
            "  location: location",
            "  properties: {",
            f"    hardwareProfile: {{ vmSize: {_str(c.instance_type)} }}",
            *os_profile,
            "    storageProfile: {",
            "      imageReference: {",
            f"        publisher: {_str(ref['publisher'])}",
            f"        offer: {_str(ref['offer'])}",
            f"        sku: {_str(ref['sku'])}",
            "        version: 'latest'",
            "      }",
            f"      osDisk: {{ createOption: 'FromImage', diskSizeGB: {c.root_volume_gib}, "
            "managedDisk: { storageAccountType: 'StandardSSD_LRS' } }",
            "    }",
            f"    networkProfile: {{ networkInterfaces: [ {{ id: {nic_id}.id }} ] }}",
            "  }",
            "  tags: {",
            f"    tier: {_str(c.tier.value)}",
            f"    environment: {_str(c.environment.value)}",
            "  }",
            "}",
            "",
        ]

    return "\n".join(lines)


def _main_bicep(plan: MigrationPlan) -> str:
    return "\n".join([
        "// Generated by IaCTranslate — subscription-scope entry point.",
        "targetScope = 'subscription'",
        "",
        f"param location string = {_str(plan.region)}",
        "param adminUsername string = 'azureuser'",
        "@secure()",
        "param adminPassword string = ''",
        "param adminSshPublicKey string = ''",
        "",
        "resource rg 'Microsoft.Resources/resourceGroups@2023-07-01' = {",
        f"  name: {_str(plan.project_name + '-rg')}",
        "  location: location",
        "}",
        "",
        "module resources 'resources.bicep' = {",
        "  name: 'resources'",
        "  scope: rg",
        "  params: {",
        "    location: location",
        "    adminUsername: adminUsername",
        "    adminPassword: adminPassword",
        "    adminSshPublicKey: adminSshPublicKey",
        "  }",
        "}",
        "",
    ])


def _readme(plan: MigrationPlan) -> str:
    return (
        f"# {plan.project_name} — Bicep (Azure)\n\n"
        "Generated by IaCTranslate, rendered from the Infrastructure Graph "
        "(see docs/adr/0010-infrastructure-graph.md and 0014), not the plan directly.\n\n"
        "Two files, the standard subscription-scope pattern: `main.bicep` creates the "
        "resource group, `resources.bicep` deploys into it as a module.\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "az login\n"
        "az deployment sub create --location "
        f"{plan.region} --template-file main.bicep \\\n"
        "  --parameters adminPassword=<a-strong-password> adminSshPublicKey=\"$(cat ~/.ssh/id_rsa.pub)\"\n"
        "```\n\n"
        "Windows instances need `adminPassword`; Linux instances need `adminSshPublicKey`. "
        "Both are required (`@secure()`/no default) — nothing is deployed with a placeholder secret.\n\n"
        "**Note:** this output is not compiled/validated locally (no `bicep`/`az` CLI in this "
        "environment) the way the Terraform output is proven with `tofu validate`. Run "
        "`az bicep build --file main.bicep` before deploying to catch any syntax issue.\n"
    )


def build_bicep_files(plan: MigrationPlan, target: Target) -> Dict[str, str]:
    """Render the plan as a Bicep project, walking the Infrastructure Graph."""
    if target.name != "azure":
        raise RendererNotSupportedError(
            f"the Bicep renderer only supports 'azure' (got '{target.name}')"
        )
    graph = build_graph(plan)
    return {
        "main.bicep": _main_bicep(plan),
        "resources.bicep": _resources_bicep(graph, plan, target),
        "README.md": _readme(plan),
    }
