"""AWS CDK (Python) renderer — the third renderer to consume the Infrastructure
Graph instead of the MigrationPlan directly (see ADR 0010), alongside
CloudFormation (0013) and Bicep (0014).

AWS-only. Emits an actual CDK app (`app.py` + `stack.py`) using the L1 (`Cfn*`)
constructs — `CfnVPC`, `CfnSubnet`, `CfnSecurityGroup`, `CfnInstance`, etc. —
not the higher-level `ec2.Vpc`/`ec2.Instance` L2 constructs. That's a deliberate
choice: the L2 constructs make their own opinionated decisions (auto-created
NAT gateways, default subnet layouts, implicit security groups) that would
silently diverge from the plan CDK is meant to express. L1 constructs are a
close, deterministic mirror of the CloudFormation resource model — so this
renderer reuses CloudFormation's own AMI-resolution helpers
(`_ami_dynamic_ref`/`_ami_parameter_name`) verbatim: `CfnInstance.image_id`
accepts the same SSM dynamic-reference string or `CfnParameter` ref that raw
CloudFormation does.

Deterministic string generation — no AI, and no local `cdk`/`aws-cdk-lib` in
this environment to `cdk synth` against (same honest limitation as Bicep).
Tests assert structural properties (balanced parens, one construct per graph
node, correct image wiring) rather than a real synth.
"""
from __future__ import annotations

from typing import Dict, List

from ..graph import EdgeKind, InfrastructureGraph, NodeKind, build_graph
from ..models import MigrationPlan, terraform_safe_name
from ..targets.base import Target
from .cloudformation import _ami_dynamic_ref, _ami_parameter_name, _cid


class RendererNotSupportedError(ValueError):
    pass


def _var(prefix: str, name: str) -> str:
    """A valid Python identifier for a construct variable."""
    return prefix + "_" + terraform_safe_name(name)


def _py_str(s: object) -> str:
    return repr(str(s))


def _class_name(project_name: str) -> str:
    safe = terraform_safe_name(project_name)
    return "".join(p.capitalize() for p in safe.split("_")) + "Stack"


def _stack_py(graph: InfrastructureGraph, plan: MigrationPlan, target: Target) -> str:
    lines: List[str] = [
        "\"\"\"Generated by IaCTranslate — rendered from the Infrastructure Graph",
        "(see docs/adr/0010-infrastructure-graph.md and 0015), not the plan directly.\"\"\"",
        "from aws_cdk import CfnParameter, Stack, Tags",
        "from aws_cdk import aws_ec2 as ec2",
        "from aws_cdk import aws_elasticloadbalancingv2 as elbv2",
        "from constructs import Construct",
        "",
        "",
        f"class {_class_name(plan.project_name)}(Stack):",
        "    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:",
        "        super().__init__(scope, construct_id, **kwargs)",
        "",
    ]

    def add(line: str) -> None:
        lines.append("        " + line if line else "")

    vpc_node = graph.nodes_of(NodeKind.VPC)[0]
    vpc_var = _var("vpc", vpc_node.name)
    add(f"{vpc_var} = ec2.CfnVPC(")
    add(f"    self, {_py_str(_cid('Vpc', vpc_node.name))},")
    add(f"    cidr_block={_py_str(vpc_node.attributes['cidr'])},")
    add("    enable_dns_hostnames=True, enable_dns_support=True,")
    add(")")
    add(f"Tags.of({vpc_var}).add('Name', {_py_str(vpc_node.name)})")
    add("")

    igw_var = None
    if vpc_node.attributes.get("internet_gateway"):
        igw_var = _var("igw", vpc_node.name)
        attach_var = _var("attach", vpc_node.name)
        add(f"{igw_var} = ec2.CfnInternetGateway(self, {_py_str(_cid('Igw', vpc_node.name))})")
        add(f"{attach_var} = ec2.CfnVPCGatewayAttachment(")
        add(f"    self, {_py_str(_cid('VpcGatewayAttachment', vpc_node.name))},")
        add(f"    vpc_id={vpc_var}.attr_vpc_id, internet_gateway_id={igw_var}.attr_internet_gateway_id,")
        add(")")
        add("")

    subnet_var_by_node: Dict[str, str] = {}
    public_subnet_vars: List[str] = []
    private_subnet_vars: List[str] = []
    for subnet in graph.nodes_of(NodeKind.SUBNET):
        svar = _var("subnet", subnet.name)
        subnet_var_by_node[subnet.id] = svar
        is_public = subnet.attributes["tier"] == "public"
        add(f"{svar} = ec2.CfnSubnet(")
        add(f"    self, {_py_str(_cid('Subnet', subnet.name))},")
        add(f"    vpc_id={vpc_var}.attr_vpc_id,")
        add(f"    cidr_block={_py_str(subnet.attributes['cidr'])},")
        add(
            f"    availability_zone=Stack.of(self).availability_zones"
            f"[{subnet.attributes['availability_zone_index']}],"
        )
        add(f"    map_public_ip_on_launch={is_public},")
        add(")")
        add(f"Tags.of({svar}).add('Name', {_py_str(subnet.name)})")
        add(f"Tags.of({svar}).add('Tier', {_py_str(subnet.attributes['tier'])})")
        add("")
        (public_subnet_vars if is_public else private_subnet_vars).append(svar)

    if igw_var and public_subnet_vars:
        rt_var = _var("route_table", "public")
        add(f"{rt_var} = ec2.CfnRouteTable(")
        add(f"    self, {_py_str(_cid('RouteTable', 'public'))}, vpc_id={vpc_var}.attr_vpc_id,")
        add(")")
        add("ec2.CfnRoute(")
        add(f"    self, {_py_str(_cid('Route', 'public-internet'))},")
        add(f"    route_table_id={rt_var}.attr_route_table_id,")
        add("    destination_cidr_block='0.0.0.0/0',")
        add(f"    gateway_id={igw_var}.attr_internet_gateway_id,")
        add(f").add_dependency({attach_var})")
        for svar in public_subnet_vars:
            add(
                f"ec2.CfnSubnetRouteTableAssociation(self, {_py_str(_cid('RouteTableAssoc', svar))}, "
                f"subnet_id={svar}.attr_subnet_id, route_table_id={rt_var}.attr_route_table_id)"
            )
        add("")

    if vpc_node.attributes.get("nat_gateway") and public_subnet_vars and private_subnet_vars:
        eip_var = _var("eip", "nat")
        nat_var = _var("nat", "nat")
        add(f"{eip_var} = ec2.CfnEIP(self, {_py_str(_cid('NatEip', 'nat'))}, domain='vpc')")
        add(f"{nat_var} = ec2.CfnNatGateway(")
        add(f"    self, {_py_str(_cid('NatGateway', 'nat'))},")
        add(f"    allocation_id={eip_var}.attr_allocation_id, subnet_id={public_subnet_vars[0]}.attr_subnet_id,")
        add(")")
        priv_rt_var = _var("route_table", "private")
        add(f"{priv_rt_var} = ec2.CfnRouteTable(")
        add(f"    self, {_py_str(_cid('RouteTable', 'private'))}, vpc_id={vpc_var}.attr_vpc_id,")
        add(")")
        add("ec2.CfnRoute(")
        add(f"    self, {_py_str(_cid('Route', 'private-nat'))},")
        add(f"    route_table_id={priv_rt_var}.attr_route_table_id,")
        add("    destination_cidr_block='0.0.0.0/0',")
        add(f"    nat_gateway_id={nat_var}.attr_nat_gateway_id,")
        add(")")
        for svar in private_subnet_vars:
            add(
                f"ec2.CfnSubnetRouteTableAssociation(self, {_py_str(_cid('RouteTableAssoc', svar))}, "
                f"subnet_id={svar}.attr_subnet_id, route_table_id={priv_rt_var}.attr_route_table_id)"
            )
        add("")

    sg_var_by_node: Dict[str, str] = {}
    for sg in graph.nodes_of(NodeKind.SECURITY_GROUP):
        gvar = _var("sg", sg.name)
        sg_var_by_node[sg.id] = gvar
        add(f"{gvar} = ec2.CfnSecurityGroup(")
        add(f"    self, {_py_str(_cid('Sg', sg.name))},")
        add(f"    group_description={_py_str(sg.attributes.get('description') or sg.name)},")
        add(f"    vpc_id={vpc_var}.attr_vpc_id,")
        add("    security_group_ingress=[")
        for rule in sg.attributes["ingress"]:
            for cidr in rule["cidr_blocks"]:
                add(
                    "        ec2.CfnSecurityGroup.IngressProperty("
                    f"ip_protocol={_py_str(rule['protocol'])}, "
                    f"from_port={rule['from_port']}, to_port={rule['to_port']}, "
                    f"cidr_ip={_py_str(cidr)}, description={_py_str(rule['description'])}),"
                )
        add("    ],")
        add(")")
        add(f"Tags.of({gvar}).add('Name', {_py_str(sg.name)})")
        add("")

    image_keys = sorted({n.attributes["image_key"] for n in graph.nodes_of(NodeKind.INSTANCE)})
    param_var_by_key: Dict[str, str] = {}
    for key in image_keys:
        if _ami_dynamic_ref(key) is None:
            pvar = _var("param", key)
            param_var_by_key[key] = pvar
            description = f"AMI id for image '{key}' (no public SSM alias for this OS)"
            add(f"{pvar} = CfnParameter(")
            add(f"    self, {_py_str(_ami_parameter_name(key))}, type='AWS::EC2::Image::Id',")
            add(f"    description={_py_str(description)},")
            add(")")
            add("")

    instance_var_by_name: Dict[str, str] = {}
    for c in plan.compute:
        inst = next(n for n in graph.nodes_of(NodeKind.INSTANCE) if n.name == c.vm_name)
        ivar = _var("inst", inst.name)
        instance_var_by_name[inst.name] = ivar
        key = inst.attributes["image_key"]
        dyn = _ami_dynamic_ref(key)
        image_expr = _py_str(dyn) if dyn is not None else f"{param_var_by_key[key]}.value_as_string"

        placed_in = graph.out_edges(inst.id, EdgeKind.PLACED_IN)
        secured_by = graph.out_edges(inst.id, EdgeKind.SECURED_BY)
        subnet_var = subnet_var_by_node[placed_in[0].target] if placed_in else None
        sg_vars = [sg_var_by_node[e.target] for e in secured_by if e.target in sg_var_by_node]

        block_devices = [
            "        ec2.CfnInstance.BlockDeviceMappingProperty(\n"
            "            device_name='/dev/xvda',\n"
            "            ebs=ec2.CfnInstance.EbsProperty("
            f"volume_size={inst.attributes['root_volume_gib']}, volume_type='gp3'),\n"
            "        ),"
        ]
        for i, size in enumerate(inst.attributes.get("extra_volumes_gib") or []):
            dev = chr(ord("f") + i)
            block_devices.append(
                "        ec2.CfnInstance.BlockDeviceMappingProperty(\n"
                f"            device_name='/dev/xvd{dev}',\n"
                f"            ebs=ec2.CfnInstance.EbsProperty(volume_size={size}, volume_type='gp3'),\n"
                "        ),"
            )

        add(f"{ivar} = ec2.CfnInstance(")
        add(f"    self, {_py_str(_cid('Instance', inst.name))},")
        add(f"    instance_type={_py_str(inst.attributes['instance_type'])},")
        add(f"    image_id={image_expr},")
        if subnet_var:
            add(f"    subnet_id={subnet_var}.attr_subnet_id,")
        add(f"    security_group_ids=[{', '.join(f'{v}.attr_group_id' for v in sg_vars)}],")
        add("    block_device_mappings=[")
        for bd in block_devices:
            add(bd)
        add("    ],")
        add(")")
        add(f"Tags.of({ivar}).add('Name', {_py_str(inst.name)})")
        add(f"Tags.of({ivar}).add('Tier', {_py_str(inst.attributes['tier'])})")
        add(f"Tags.of({ivar}).add('Environment', {_py_str(inst.attributes['environment'])})")
        add("")

    for lb in graph.nodes_of(NodeKind.LOAD_BALANCER):
        lvar = _var("lb", lb.name)
        lb_subnet_vars = [
            subnet_var_by_node[e.target] for e in graph.out_edges(lb.id, EdgeKind.PLACED_IN)
        ]
        lb_sg_vars = [sg_var_by_node[e.target] for e in graph.out_edges(lb.id, EdgeKind.SECURED_BY)]
        add(f"{lvar} = elbv2.CfnLoadBalancer(")
        add(f"    self, {_py_str(_cid('Lb', lb.name))},")
        add("    type='application',")
        add(f"    scheme={_py_str('internet-facing' if lb.attributes['internet_facing'] else 'internal')},")
        add(f"    subnets=[{', '.join(f'{v}.attr_subnet_id' for v in lb_subnet_vars)}],")
        add(f"    security_groups=[{', '.join(f'{v}.attr_group_id' for v in lb_sg_vars)}],")
        add(")")

        target_vars = [
            instance_var_by_name[graph.node(e.target).name]
            for e in graph.out_edges(lb.id, EdgeKind.FRONTS)
            if graph.node(e.target) is not None
        ]
        for listener in lb.attributes["listeners"]:
            listener_suffix = f"{lb.name}-{listener['listener_port']}"
            tgvar = _var("tg", listener_suffix)
            tg_cid = _cid("TargetGroup", listener_suffix)
            add(f"{tgvar} = elbv2.CfnTargetGroup(")
            add(f"    self, {_py_str(tg_cid)},")
            add(f"    port={listener['target_port']}, protocol={_py_str(listener['protocol'])},")
            add(f"    vpc_id={vpc_var}.attr_vpc_id, target_type='instance',")
            add(f"    health_check_path={_py_str(lb.attributes['health_check_path'])},")
            add("    targets=[")
            for tv in target_vars:
                add(
                    f"        elbv2.CfnTargetGroup.TargetDescriptionProperty("
                    f"id={tv}.ref, port={listener['target_port']}),"
                )
            add("    ],")
            add(")")
            lvar_listener = _var("listener", listener_suffix)
            listener_cid = _cid("Listener", listener_suffix)
            add(f"{lvar_listener} = elbv2.CfnListener(")
            add(f"    self, {_py_str(listener_cid)},")
            add(f"    load_balancer_arn={lvar}.ref,")
            add(f"    port={listener['listener_port']}, protocol={_py_str(listener['protocol'])},")
            add(
                f"    default_actions=[elbv2.CfnListener.ActionProperty("
                f"type='forward', target_group_arn={tgvar}.ref)],"
            )
            add(")")
        add("")

    return "\n".join(lines) + "\n"


def _app_py(plan: MigrationPlan) -> str:
    cls = _class_name(plan.project_name)
    return "\n".join([
        "#!/usr/bin/env python3",
        "import aws_cdk as cdk",
        "",
        f"from stack import {cls}",
        "",
        "app = cdk.App()",
        f"{cls}(",
        "    app,",
        f"    {_py_str(plan.project_name + '-stack')},",
        f"    env=cdk.Environment(region={_py_str(plan.region)}),",
        ")",
        "app.synth()",
        "",
    ])


def _readme(plan: MigrationPlan) -> str:
    return (
        f"# {plan.project_name} — AWS CDK (Python)\n\n"
        "Generated by IaCTranslate, rendered from the Infrastructure Graph "
        "(see docs/adr/0010-infrastructure-graph.md and 0015), using the L1 "
        "(`Cfn*`) constructs for a deterministic, direct mirror of the "
        "topology — not the opinionated L2 `ec2.Vpc`/`ec2.Instance` constructs.\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "pip install -r requirements.txt\n"
        "cdk bootstrap   # once per account/region\n"
        "cdk synth       # review the generated CloudFormation\n"
        "cdk deploy\n"
        "```\n\n"
        "**Note:** this output is not synthesized locally (no `aws-cdk-lib`/`cdk` "
        "CLI in this environment) the way the Terraform output is proven with "
        "`tofu validate`. Run `cdk synth` before deploying to catch any issue.\n"
    )


def build_cdk_files(plan: MigrationPlan, target: Target) -> Dict[str, str]:
    """Render the plan as an AWS CDK (Python) app, walking the Infrastructure Graph."""
    if target.name != "aws":
        raise RendererNotSupportedError(
            f"the AWS CDK renderer only supports 'aws' (got '{target.name}')"
        )
    graph = build_graph(plan)
    return {
        "app.py": _app_py(plan),
        "stack.py": _stack_py(graph, plan, target),
        "requirements.txt": "aws-cdk-lib>=2.140.0\nconstructs>=10.0.0\n",
        "cdk.json": '{\n  "app": "python3 app.py"\n}\n',
        "README.md": _readme(plan),
    }
