"""Pulumi (Python) renderer — an alternative IaC output to Terraform.

Renders the same validated MigrationPlan as a Pulumi program (pulumi-aws),
proving the pipeline is renderer-agnostic. Currently supports the AWS target;
Azure/GCP raise a clear error until their Pulumi providers are wired.

Deterministic string generation — no AI. The emitted `__main__.py` is
syntactically valid Python (compiled in tests).
"""
from __future__ import annotations

from typing import Dict, List

from ..generator.renderer import _assign_subnets
from ..models import MigrationPlan, SubnetTier, terraform_safe_name
from ..targets.base import Target


class RendererNotSupportedError(ValueError):
    pass


def _py_str(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ingress_block(rule) -> str:
    cidrs = ", ".join(_py_str(c) for c in rule.cidr_blocks)
    return (
        "        {"
        f'"description": {_py_str(rule.description)}, '
        f'"protocol": {_py_str(rule.protocol)}, '
        f'"from_port": {rule.from_port}, "to_port": {rule.to_port}, '
        f'"cidr_blocks": [{cidrs}]'
        "},"
    )


def _main_py(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)
    sg_resource = {sg.name: sg.resource_name for sg in net.security_groups}

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (AWS).',
        "",
        "Equivalent to the Terraform output; deploy with `pulumi up`.",
        '"""',
        "import pulumi",
        "import pulumi_aws as aws",
        "",
        f"region = {_py_str(plan.region)}",
        'provider = aws.Provider("aws", region=region)',
        "opts = pulumi.ResourceOptions(provider=provider)",
        'azs = aws.get_availability_zones(state="available")',
        "",
        "# --- Network -------------------------------------------------------------",
        'vpc = aws.ec2.Vpc(',
        '    "vpc",',
        f"    cidr_block={_py_str(net.vpc_cidr)},",
        "    enable_dns_hostnames=True,",
        "    enable_dns_support=True,",
        f'    tags={{"Name": {_py_str(plan.project_name + "-vpc")}}},',
        "    opts=opts,",
        ")",
    ]

    if net.internet_gateway:
        lines += [
            'igw = aws.ec2.InternetGateway("igw", vpc_id=vpc.id,',
            f'    tags={{"Name": {_py_str(plan.project_name + "-igw")}}}, opts=opts)',
        ]

    lines.append("")
    for s in net.subnets:
        public = s.tier == SubnetTier.PUBLIC
        lines += [
            f"subnet_{s.resource_name} = aws.ec2.Subnet(",
            f"    {_py_str(s.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    cidr_block={_py_str(s.cidr)},",
            f"    availability_zone=azs.names[{s.availability_zone_index}],",
            f"    map_public_ip_on_launch={public},",
            f'    tags={{"Name": {_py_str(s.name)}, "Tier": {_py_str(s.tier.value)}}},',
            "    opts=opts,",
            ")",
        ]

    lines += ["", "# --- Security groups -----------------------------------------------------"]
    for sg in net.security_groups:
        ingress = "\n".join(_ingress_block(r) for r in sg.ingress)
        lines += [
            f"sg_{sg.resource_name} = aws.ec2.SecurityGroup(",
            f"    {_py_str(sg.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    description={_py_str(sg.description or sg.name)},",
            "    ingress=[",
            ingress,
            "    ],",
            '    egress=[{"protocol": "-1", "from_port": 0, "to_port": 0, '
            '"cidr_blocks": ["0.0.0.0/0"]}],',
            f'    tags={{"Name": {_py_str(sg.name)}}},',
            "    opts=opts,",
            ")",
        ]

    # AMI lookups, one per distinct OS image.
    lines += ["", "# --- AMI lookups ---------------------------------------------------------"]
    image_keys = sorted({c.image_key for c in plan.compute})
    for key in image_keys:
        ref = target.image_reference(key)
        owners = ", ".join(_py_str(o) for o in ref.get("owners", []))
        name = _py_str(ref.get("name", "*"))
        var = terraform_safe_name(key)
        lines += [
            f"ami_{var} = aws.ec2.get_ami(",
            "    most_recent=True,",
            f"    owners=[{owners}],",
            f'    filters=[{{"name": "name", "values": [{name}]}},',
            '             {"name": "virtualization-type", "values": ["hvm"]}],',
            ")",
        ]

    # Instances.
    lines += ["", "# --- Instances -----------------------------------------------------------"]
    for c in plan.compute:
        ami_var = terraform_safe_name(c.image_key)
        subnet_res = subnet_of[c.vm_name]
        sg_res = sg_resource.get(c.security_group)
        sg_ref = f"sg_{sg_res}.id" if sg_res else "None"
        lines += [
            f"inst_{c.resource_name} = aws.ec2.Instance(",
            f"    {_py_str(c.resource_name)},",
            f"    instance_type={_py_str(c.instance_type)},",
            f"    ami=ami_{ami_var}.id,",
            f"    subnet_id=subnet_{subnet_res}.id,",
            f"    vpc_security_group_ids=[{sg_ref}],",
            f'    root_block_device={{"volume_size": {c.root_volume_gib}, "volume_type": "gp3"}},',
            f'    tags={{"Name": {_py_str(c.vm_name)}, "Tier": {_py_str(c.tier.value)}, '
            f'"Environment": {_py_str(c.environment.value)}}},',
            "    opts=opts,",
            ")",
        ]
        if c.external_id:
            # Brownfield: adopt the existing instance rather than recreate it.
            lines[-1] = (
                "    opts=pulumi.ResourceOptions(provider=provider, "
                f"import_={_py_str(c.external_id)}),"
            )
            lines.append(")")

    lines += [
        "",
        'pulumi.export("vpc_id", vpc.id)',
        'pulumi.export("instance_count", ' + str(plan.vm_count) + ")",
        "",
    ]
    return "\n".join(lines)


def _pulumi_yaml(plan: MigrationPlan) -> str:
    return (
        f"name: {terraform_safe_name(plan.project_name)}\n"
        "runtime:\n  name: python\n"
        f"description: IaCTranslate-generated migration of {plan.project_name} to AWS.\n"
    )


def _readme(plan: MigrationPlan) -> str:
    return (
        f"# {plan.project_name} — Pulumi (AWS)\n\n"
        "Generated by IaCTranslate as an alternative to the Terraform output.\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "python -m venv venv && source venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        "pulumi stack init dev\n"
        "pulumi up\n"
        "```\n\n"
        "OS images resolve automatically via `aws.ec2.get_ami`. "
        "Configure AWS credentials as usual (env vars or profile).\n"
    )


def build_pulumi_files(plan: MigrationPlan, target: Target) -> Dict[str, str]:
    """Render the plan as a Pulumi Python project (AWS only for now)."""
    if target.name != "aws":
        raise RendererNotSupportedError(
            f"the Pulumi renderer currently supports only the AWS target, not '{target.name}'"
        )
    return {
        "__main__.py": _main_py(plan, target),
        "Pulumi.yaml": _pulumi_yaml(plan),
        "requirements.txt": "pulumi>=3.0.0,<4.0.0\npulumi-aws>=6.0.0,<7.0.0\n",
        "README.md": _readme(plan),
    }
