"""Pulumi (Python) renderer — an alternative IaC output to Terraform.

Renders the same validated MigrationPlan as a Pulumi program, proving the
pipeline is renderer-agnostic. Supports all three targets: AWS (pulumi-aws),
Azure (pulumi-azure), and GCP (pulumi-gcp).

Deterministic string generation — no AI. The emitted `__main__.py` is
syntactically valid Python (compiled in tests).
"""
from __future__ import annotations

from typing import Dict, List

from ..generator.renderer import _assign_subnets
from ..models import MigrationPlan, SubnetTier, terraform_safe_name
from ..targets.base import Target


class RendererNotSupportedError(ValueError):
    pass


def _py_str(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ingress_block(rule) -> str:
    cidrs = ", ".join(_py_str(c) for c in rule.cidr_blocks)
    return (
        "        {"
        f'"description": {_py_str(rule.description)}, '
        f'"protocol": {_py_str(rule.protocol)}, '
        f'"from_port": {rule.from_port}, "to_port": {rule.to_port}, '
        f'"cidr_blocks": [{cidrs}]'
        "},"
    )


def _aws_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)
    sg_resource = {sg.name: sg.resource_name for sg in net.security_groups}
    has_https = any(listener.protocol == "HTTPS" for lb in net.load_balancers for listener in lb.listeners)

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (AWS).',
        "",
        "Equivalent to the Terraform output; deploy with `pulumi up`.",
        '"""',
        "import pulumi",
        "import pulumi_aws as aws",
        "",
        f"region = {_py_str(plan.region)}",
        'provider = aws.Provider("aws", region=region)',
        "opts = pulumi.ResourceOptions(provider=provider)",
        'azs = aws.get_availability_zones(state="available")',
    ]
    if has_https:
        lines += [
            "config = pulumi.Config()",
            '# Required for HTTPS listeners - no ACM certificate can be known at '
            "generation time.",
            'acm_certificate_arn = config.get("acmCertificateArn") or ""',
        ]
    lines += [
        "",
        "# --- Network -------------------------------------------------------------",
        'vpc = aws.ec2.Vpc(',
        '    "vpc",',
        f"    cidr_block={_py_str(net.vpc_cidr)},",
        "    enable_dns_hostnames=True,",
        "    enable_dns_support=True,",
        f'    tags={{"Name": {_py_str(plan.project_name + "-vpc")}}},',
        "    opts=opts,",
        ")",
    ]

    if net.internet_gateway:
        lines += [
            'igw = aws.ec2.InternetGateway("igw", vpc_id=vpc.id,',
            f'    tags={{"Name": {_py_str(plan.project_name + "-igw")}}}, opts=opts)',
        ]

    lines.append("")
    for s in net.subnets:
        public = s.tier == SubnetTier.PUBLIC
        lines += [
            f"subnet_{s.resource_name} = aws.ec2.Subnet(",
            f"    {_py_str(s.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    cidr_block={_py_str(s.cidr)},",
            f"    availability_zone=azs.names[{s.availability_zone_index}],",
            f"    map_public_ip_on_launch={public},",
            f'    tags={{"Name": {_py_str(s.name)}, "Tier": {_py_str(s.tier.value)}}},',
            "    opts=opts,",
            ")",
        ]

    lines += ["", "# --- Security groups -----------------------------------------------------"]
    for sg in net.security_groups:
        ingress = "\n".join(_ingress_block(r) for r in sg.ingress)
        lines += [
            f"sg_{sg.resource_name} = aws.ec2.SecurityGroup(",
            f"    {_py_str(sg.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    description={_py_str(sg.description or sg.name)},",
            "    ingress=[",
            ingress,
            "    ],",
            '    egress=[{"protocol": "-1", "from_port": 0, "to_port": 0, '
            '"cidr_blocks": ["0.0.0.0/0"]}],',
            f'    tags={{"Name": {_py_str(sg.name)}}},',
            "    opts=opts,",
            ")",
        ]

    # AMI lookups, one per distinct OS image.
    lines += ["", "# --- AMI lookups ---------------------------------------------------------"]
    image_keys = sorted({c.image_key for c in plan.compute})
    for key in image_keys:
        ref = target.image_reference(key)
        owners = ", ".join(_py_str(o) for o in ref.get("owners", []))
        name = _py_str(ref.get("name", "*"))
        var = terraform_safe_name(key)
        lines += [
            f"ami_{var} = aws.ec2.get_ami(",
            "    most_recent=True,",
            f"    owners=[{owners}],",
            f'    filters=[{{"name": "name", "values": [{name}]}},',
            '             {"name": "virtualization-type", "values": ["hvm"]}],',
            ")",
        ]

    # Instances.
    lines += ["", "# --- Instances -----------------------------------------------------------"]
    for c in plan.compute:
        ami_var = terraform_safe_name(c.image_key)
        subnet_res = subnet_of[c.vm_name]
        sg_res = sg_resource.get(c.security_group)
        sg_ref = f"sg_{sg_res}.id" if sg_res else "None"
        lines += [
            f"inst_{c.resource_name} = aws.ec2.Instance(",
            f"    {_py_str(c.resource_name)},",
            f"    instance_type={_py_str(c.instance_type)},",
            f"    ami=ami_{ami_var}.id,",
            f"    subnet_id=subnet_{subnet_res}.id,",
            f"    vpc_security_group_ids=[{sg_ref}],",
            f'    root_block_device={{"volume_size": {c.root_volume_gib}, "volume_type": "gp3"}},',
            f'    tags={{"Name": {_py_str(c.vm_name)}, "Tier": {_py_str(c.tier.value)}, '
            f'"Environment": {_py_str(c.environment.value)}}},',
            "    opts=opts,",
            ")",
        ]
        if c.external_id:
            # Brownfield: adopt the existing instance rather than recreate it.
            lines[-1] = (
                "    opts=pulumi.ResourceOptions(provider=provider, "
                f"import_={_py_str(c.external_id)}),"
            )
            lines.append(")")

    if net.load_balancers:
        lines += ["", "# --- Load balancers --------------------------------------------------------"]
        for lb in net.load_balancers:
            lb_subnets = ", ".join(f"subnet_{s.resource_name}.id" for s in net.subnets if s.tier == lb.subnet_tier)
            lb_sg = sg_resource.get(lb.security_group)
            lines += [
                f"lb_{lb.resource_name} = aws.lb.LoadBalancer(",
                f"    {_py_str(lb.resource_name)},",
                f'    internal={not lb.internet_facing},',
                '    load_balancer_type="application",',
                f"    security_groups=[sg_{lb_sg}.id],",
                f"    subnets=[{lb_subnets}],",
                f'    tags={{"Name": {_py_str(lb.name)}}},',
                "    opts=opts,",
                ")",
            ]
            for listener in lb.listeners:
                tg = f"tg_{lb.resource_name}_{listener.listener_port}"
                lines += [
                    f"{tg} = aws.lb.TargetGroup(",
                    f"    {_py_str(lb.resource_name + '-' + str(listener.listener_port))},",
                    f"    port={listener.target_port},",
                    f"    protocol={_py_str(listener.protocol)},",
                    "    vpc_id=vpc.id,",
                    f'    health_check={{"path": {_py_str(lb.health_check_path)}}},',
                    "    opts=opts,",
                    ")",
                ]
                for vm_name in lb.targets:
                    c = next(cc for cc in plan.compute if cc.vm_name == vm_name)
                    lines += [
                        "aws.lb.TargetGroupAttachment(",
                        f"    {_py_str(f'{lb.resource_name}-{listener.listener_port}-{c.resource_name}')},",
                        f"    target_group_arn={tg}.arn,",
                        f"    target_id=inst_{c.resource_name}.id,",
                        f"    port={listener.target_port},",
                        "    opts=opts,",
                        ")",
                    ]
                listener_kwargs = (
                    ['    ssl_policy="ELBSecurityPolicy-2016-08",', "    certificate_arn=acm_certificate_arn,"]
                    if listener.protocol == "HTTPS"
                    else []
                )
                lines += [
                    "aws.lb.Listener(",
                    f"    {_py_str(lb.resource_name + '-' + str(listener.listener_port))},",
                    f"    load_balancer_arn=lb_{lb.resource_name}.arn,",
                    f"    port={listener.listener_port},",
                    f"    protocol={_py_str(listener.protocol)},",
                    *listener_kwargs,
                    f'    default_actions=[{{"type": "forward", "target_group_arn": {tg}.arn}}],',
                    "    opts=opts,",
                    ")",
                ]

    lines += [
        "",
        'pulumi.export("vpc_id", vpc.id)',
        'pulumi.export("instance_count", ' + str(plan.vm_count) + ")",
        "",
    ]
    return "\n".join(lines)


def _azure_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)
    sg_resource = {sg.name: sg.resource_name for sg in net.security_groups}

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (Azure)."""',
        "import pulumi",
        "import pulumi_azure as azure",
        "",
        "config = pulumi.Config()",
        'admin_username = config.get("adminUsername") or "azureuser"',
        'admin_password = config.get_secret("adminPassword") or "REPLACE_ME_Str0ng!Pass"',
        'admin_ssh_public_key = config.get("adminSshPublicKey") or "ssh-rsa REPLACE_ME"',
        f"location = {_py_str(plan.region)}",
        "",
        "rg = azure.core.ResourceGroup(",
        '    "rg",',
        f"    name={_py_str(plan.project_name + '-rg')},",
        "    location=location,",
        ")",
        "vnet = azure.network.VirtualNetwork(",
        '    "vnet",',
        "    resource_group_name=rg.name,",
        "    location=rg.location,",
        f"    address_spaces=[{_py_str(net.vpc_cidr)}],",
        ")",
    ]

    for s in net.subnets:
        lines += [
            f"subnet_{s.resource_name} = azure.network.Subnet(",
            f"    {_py_str(s.resource_name)},",
            "    resource_group_name=rg.name,",
            "    virtual_network_name=vnet.name,",
            f"    address_prefixes=[{_py_str(s.cidr)}],",
            ")",
        ]

    # NSGs with security rules.
    for sg in net.security_groups:
        rules = []
        for i, r in enumerate(sg.ingress):
            port = f"{r.from_port}" if r.from_port == r.to_port else f"{r.from_port}-{r.to_port}"
            src = r.cidr_blocks[0] if r.cidr_blocks else "*"
            rules.append(
                "        {"
                f'"name": {_py_str("rule-" + str(i))}, "priority": {100 + i * 10}, '
                '"direction": "Inbound", "access": "Allow", '
                f'"protocol": {_py_str(r.protocol.capitalize())}, '
                '"source_port_range": "*", '
                f'"destination_port_range": {_py_str(port)}, '
                f'"source_address_prefix": {_py_str(src)}, '
                '"destination_address_prefix": "*"},'
            )
        lines += [
            f"nsg_{sg.resource_name} = azure.network.NetworkSecurityGroup(",
            f"    {_py_str(sg.resource_name)},",
            "    resource_group_name=rg.name,",
            "    location=rg.location,",
            "    security_rules=[",
            *rules,
            "    ],",
            ")",
        ]

    backend_pool_ref_by_vm_name: Dict[str, str] = {}
    if net.load_balancers:
        lines += ["", "# --- Load balancers ---------------------------------------------------"]
        for lb in net.load_balancers:
            lb_var = f"lb_{lb.resource_name}"
            if lb.internet_facing:
                lines += [
                    f"pip_{lb.resource_name} = azure.network.PublicIp(",
                    f"    {_py_str(lb.resource_name)},",
                    "    resource_group_name=rg.name, location=rg.location,",
                    '    allocation_method="Static", sku="Standard",',
                    ")",
                ]
                frontend = f'{{"name": "frontend", "public_ip_address_id": pip_{lb.resource_name}.id}}'
            else:
                first_subnet = next(s for s in net.subnets if s.tier == lb.subnet_tier)
                frontend = (
                    '{"name": "frontend", '
                    f'"subnet_id": subnet_{first_subnet.resource_name}.id, '
                    '"private_ip_address_allocation": "Dynamic"}'
                )
            lines += [
                f"{lb_var} = azure.lb.LoadBalancer(",
                f"    {_py_str(lb.resource_name)},",
                "    resource_group_name=rg.name, location=rg.location,",
                '    sku="Standard",',
                f"    frontend_ip_configurations=[{frontend}],",
                ")",
                f"pool_{lb.resource_name} = azure.lb.BackendAddressPool(",
                f"    {_py_str(lb.resource_name)},",
                f"    resource_group_name=rg.name, loadbalancer_id={lb_var}.id,",
                ")",
            ]
            for listener in lb.listeners:
                suffix = f"{lb.resource_name}_{listener.listener_port}"
                lines += [
                    f"probe_{suffix} = azure.lb.Probe(",
                    f"    {_py_str(suffix)},",
                    f"    resource_group_name=rg.name, loadbalancer_id={lb_var}.id,",
                    f'    protocol="Tcp", port={listener.target_port},',
                    ")",
                    "azure.lb.Rule(",
                    f"    {_py_str(suffix)},",
                    f"    resource_group_name=rg.name, loadbalancer_id={lb_var}.id,",
                    '    protocol="Tcp",',
                    f"    frontend_port={listener.listener_port}, backend_port={listener.target_port},",
                    '    frontend_ip_configuration_name="frontend",',
                    f"    backend_address_pool_ids=[pool_{lb.resource_name}.id],",
                    f"    probe_id=probe_{suffix}.id,",
                    ")",
                ]
            for vm_name in lb.targets:
                backend_pool_ref_by_vm_name[vm_name] = f"pool_{lb.resource_name}.id"

    for c in plan.compute:
        ref = target.image_reference(c.image_key)
        nic = f"nic_{c.resource_name}"
        subnet_res = subnet_of[c.vm_name]
        sg_res = sg_resource.get(c.security_group)
        is_windows = c.image_key.startswith("windows")
        backend_pool_ref = backend_pool_ref_by_vm_name.get(c.vm_name)
        # A fronted instance gets its public entry point via the load balancer,
        # not its own public IP - giving it one too would bypass the LB.
        public = c.subnet_tier == SubnetTier.PUBLIC and not backend_pool_ref
        if public:
            lines += [
                f"pip_{c.resource_name} = azure.network.PublicIp(",
                f"    {_py_str(c.resource_name)},",
                "    resource_group_name=rg.name, location=rg.location,",
                '    allocation_method="Static", sku="Standard",',
                ")",
            ]
        ip_cfg = (
            '        "name": "internal", '
            f'"subnet_id": subnet_{subnet_res}.id, '
            '"private_ip_address_allocation": "Dynamic"'
        )
        if public:
            ip_cfg += f', "public_ip_address_id": pip_{c.resource_name}.id'
        if backend_pool_ref:
            ip_cfg += f', "load_balancer_backend_address_pools_ids": [{backend_pool_ref}]'
        lines += [
            f"{nic} = azure.network.NetworkInterface(",
            f"    {_py_str(c.resource_name)},",
            "    resource_group_name=rg.name, location=rg.location,",
            "    ip_configurations=[{" + ip_cfg + "}],",
            ")",
        ]
        if sg_res:
            lines += [
                "azure.network.NetworkInterfaceSecurityGroupAssociation(",
                f"    {_py_str(c.resource_name)},",
                f"    network_interface_id={nic}.id,",
                f"    network_security_group_id=nsg_{sg_res}.id,",
                ")",
            ]
        vm_type = "WindowsVirtualMachine" if is_windows else "LinuxVirtualMachine"
        cred = (
            "    admin_password=admin_password,"
            if is_windows
            else "    admin_ssh_keys=[{\"username\": admin_username, "
                 '"public_key": admin_ssh_public_key}],'
        )
        lines += [
            f"inst_{c.resource_name} = azure.compute.{vm_type}(",
            f"    {_py_str(c.resource_name)},",
            "    resource_group_name=rg.name, location=rg.location,",
            f"    size={_py_str(c.instance_type)},",
            "    admin_username=admin_username,",
            cred,
            f"    network_interface_ids=[{nic}.id],",
            '    os_disk={"caching": "ReadWrite", "storage_account_type": "StandardSSD_LRS", '
            f'"disk_size_gb": {c.root_volume_gib}}},',
            "    source_image_reference={"
            f'"publisher": {_py_str(ref["publisher"])}, '
            f'"offer": {_py_str(ref["offer"])}, '
            f'"sku": {_py_str(ref["sku"])}, "version": "latest"}},',
            ")",
        ]

    lines += ["", 'pulumi.export("resource_group", rg.name)', ""]
    return "\n".join(lines)


def _gcp_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (GCP)."""',
        "import pulumi",
        "import pulumi_gcp as gcp",
        "",
        "config = pulumi.Config()",
        'project = config.get("gcpProject") or "REPLACE_ME_PROJECT_ID"',
        f"region = {_py_str(plan.region)}",
        f"zone = {_py_str(plan.region + '-a')}",
        "",
        "network = gcp.compute.Network(",
        '    "network",',
        "    auto_create_subnetworks=False,",
        "    project=project,",
        ")",
    ]

    for s in net.subnets:
        lines += [
            f"subnet_{s.resource_name} = gcp.compute.Subnetwork(",
            f"    {_py_str(s.resource_name)},",
            f"    ip_cidr_range={_py_str(s.cidr)},",
            "    region=region, network=network.id,",
            "    private_ip_google_access=True, project=project,",
            ")",
        ]

    # A firewall per security group, scoped to its tag.
    for sg in net.security_groups:
        tcp_ports = sorted({str(r.from_port) for r in sg.ingress if r.protocol.lower() == "tcp"})
        ports = ", ".join(_py_str(p) for p in tcp_ports) or '"22"'
        srcs = sorted({c for r in sg.ingress for c in r.cidr_blocks}) or ["0.0.0.0/0"]
        src_ranges = ", ".join(_py_str(c) for c in srcs)
        lines += [
            f"fw_{sg.resource_name} = gcp.compute.Firewall(",
            f"    {_py_str(sg.resource_name)},",
            "    network=network.name, project=project,",
            '    allows=[{"protocol": "tcp", "ports": [' + ports + "]}],",
            f"    source_ranges=[{src_ranges}],",
            f"    target_tags=[{_py_str(sg.name)}],",
            ")",
        ]

    fronted_vm_names = {vm for lb in net.load_balancers for vm in lb.targets}
    for c in plan.compute:
        ref = target.image_reference(c.image_key)
        subnet_res = subnet_of[c.vm_name]
        # A fronted instance's public entry point is the load balancer, not its
        # own ephemeral external IP.
        public = c.subnet_tier == SubnetTier.PUBLIC and c.vm_name not in fronted_vm_names
        access = "[{}]" if public else "[]"  # [{}] = one ephemeral external IP
        lines += [
            f"inst_{c.resource_name} = gcp.compute.Instance(",
            f"    {_py_str(c.resource_name)},",
            f"    machine_type={_py_str(c.instance_type)},",
            "    zone=zone, project=project,",
            f"    tags=[{_py_str(c.security_group)}],",
            '    boot_disk={"initialize_params": {"image": '
            f'{_py_str(ref["image"])}, "size": {c.root_volume_gib}, "type": "pd-balanced"}}}},',
            '    network_interfaces=[{"subnetwork": subnet_'
            f'{subnet_res}.id, "access_configs": {access}}}],',
            f'    labels={{"tier": {_py_str(c.tier.value)}, '
            f'"environment": {_py_str(c.environment.value)}}},',
            ")",
        ]

    if net.load_balancers:
        lines += ["", "# --- Load balancers -----------------------------------------------------"]
        for lb in net.load_balancers:
            member_refs = ", ".join(
                f"inst_{c.resource_name}.self_link" for c in plan.compute if c.vm_name in lb.targets
            )
            if lb.internet_facing:
                lines += [
                    f"hc_{lb.resource_name} = gcp.compute.HttpHealthCheck(",
                    f"    {_py_str(lb.resource_name)},",
                    f"    request_path={_py_str(lb.health_check_path)}, port={lb.listeners[0].target_port},",
                    "    project=project,",
                    ")",
                    f"pool_{lb.resource_name} = gcp.compute.TargetPool(",
                    f"    {_py_str(lb.resource_name)},",
                    "    region=region, project=project,",
                    f"    health_checks=[hc_{lb.resource_name}.self_link],",
                    f"    instances=[{member_refs}],",
                    ")",
                ]
                for listener in lb.listeners:
                    lines += [
                        "gcp.compute.ForwardingRule(",
                        f"    {_py_str(f'{lb.resource_name}-{listener.listener_port}')},",
                        "    region=region, project=project,",
                        f'    port_range={_py_str(str(listener.listener_port))},',
                        f"    target=pool_{lb.resource_name}.self_link,",
                        ")",
                    ]
            else:
                lines += [
                    f"ig_{lb.resource_name} = gcp.compute.InstanceGroup(",
                    f"    {_py_str(lb.resource_name)},",
                    "    zone=zone, project=project,",
                    f"    instances=[{member_refs}],",
                    ")",
                    f"hc_{lb.resource_name} = gcp.compute.HealthCheck(",
                    f"    {_py_str(lb.resource_name)},",
                    "    project=project,",
                    f'    tcp_health_check={{"port": {lb.listeners[0].target_port}}},',
                    ")",
                    f"bes_{lb.resource_name} = gcp.compute.RegionBackendService(",
                    f"    {_py_str(lb.resource_name)},",
                    '    region=region, project=project, protocol="TCP",',
                    '    load_balancing_scheme="INTERNAL",',
                    f"    health_checks=[hc_{lb.resource_name}.self_link],",
                    f'    backends=[{{"group": ig_{lb.resource_name}.self_link}}],',
                    ")",
                ]
                first_subnet = next(s for s in net.subnets if s.tier == lb.subnet_tier)
                for listener in lb.listeners:
                    lines += [
                        "gcp.compute.ForwardingRule(",
                        f"    {_py_str(f'{lb.resource_name}-{listener.listener_port}')},",
                        "    region=region, project=project,",
                        '    load_balancing_scheme="INTERNAL",',
                        "    network=network.id,",
                        f"    subnetwork=subnet_{first_subnet.resource_name}.id,",
                        f"    backend_service=bes_{lb.resource_name}.self_link,",
                        f'    ports=[{_py_str(str(listener.listener_port))}],',
                        ")",
                    ]

    lines += ["", 'pulumi.export("network", network.name)', ""]
    return "\n".join(lines)


# target -> (main-program builder, pip requirement, deploy note)
_CLOUD = {
    "aws": (_aws_main, "pulumi-aws>=6.0.0,<7.0.0", "AWS credentials (env vars or profile)"),
    "azure": (_azure_main, "pulumi-azure>=5.0.0,<6.0.0", "an Azure login (`az login`)"),
    "gcp": (
        _gcp_main, "pulumi-gcp>=7.0.0,<8.0.0",
        "`gcloud auth application-default login` and a project id "
        "(`pulumi config set gcpProject ...`)",
    ),
}


def _pulumi_yaml(plan: MigrationPlan) -> str:
    return (
        f"name: {terraform_safe_name(plan.project_name)}\n"
        "runtime:\n  name: python\n"
        f"description: IaCTranslate-generated migration of {plan.project_name} to {plan.target}.\n"
    )


def _readme(plan: MigrationPlan, deploy_note: str) -> str:
    return (
        f"# {plan.project_name} — Pulumi ({plan.target.upper()})\n\n"
        "Generated by IaCTranslate as an alternative to the Terraform output.\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "python -m venv venv && source venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        "pulumi stack init dev\n"
        "pulumi up\n"
        "```\n\n"
        f"OS images resolve automatically. Configure {deploy_note}.\n"
    )


def build_pulumi_files(plan: MigrationPlan, target: Target) -> Dict[str, str]:
    """Render the plan as a Pulumi Python project (AWS, Azure, or GCP)."""
    if target.name not in _CLOUD:
        raise RendererNotSupportedError(
            f"the Pulumi renderer does not support the '{target.name}' target"
        )
    main_fn, requirement, deploy_note = _CLOUD[target.name]
    return {
        "__main__.py": main_fn(plan, target),
        "Pulumi.yaml": _pulumi_yaml(plan),
        "requirements.txt": f"pulumi>=3.0.0,<4.0.0\n{requirement}\n",
        "README.md": _readme(plan, deploy_note),
    }
