"""Pulumi (Python) renderer — an alternative IaC output to Terraform.

Renders the same validated MigrationPlan as a Pulumi program, proving the
pipeline is renderer-agnostic. Supports all three targets: AWS (pulumi-aws),
Azure (pulumi-azure), and GCP (pulumi-gcp).

Deterministic string generation — no AI. The emitted `__main__.py` is
syntactically valid Python (compiled in tests).
"""
from __future__ import annotations

from typing import Dict, List

from ..generator.renderer import _assign_subnets
from ..models import MigrationPlan, SubnetTier, terraform_safe_name
from ..targets.base import Target


class RendererNotSupportedError(ValueError):
    pass


def _py_str(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ingress_block(rule) -> str:
    cidrs = ", ".join(_py_str(c) for c in rule.cidr_blocks)
    return (
        "        {"
        f'"description": {_py_str(rule.description)}, '
        f'"protocol": {_py_str(rule.protocol)}, '
        f'"from_port": {rule.from_port}, "to_port": {rule.to_port}, '
        f'"cidr_blocks": [{cidrs}]'
        "},"
    )


def _aws_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)
    sg_resource = {sg.name: sg.resource_name for sg in net.security_groups}

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (AWS).',
        "",
        "Equivalent to the Terraform output; deploy with `pulumi up`.",
        '"""',
        "import pulumi",
        "import pulumi_aws as aws",
        "",
        f"region = {_py_str(plan.region)}",
        'provider = aws.Provider("aws", region=region)',
        "opts = pulumi.ResourceOptions(provider=provider)",
        'azs = aws.get_availability_zones(state="available")',
        "",
        "# --- Network -------------------------------------------------------------",
        'vpc = aws.ec2.Vpc(',
        '    "vpc",',
        f"    cidr_block={_py_str(net.vpc_cidr)},",
        "    enable_dns_hostnames=True,",
        "    enable_dns_support=True,",
        f'    tags={{"Name": {_py_str(plan.project_name + "-vpc")}}},',
        "    opts=opts,",
        ")",
    ]

    if net.internet_gateway:
        lines += [
            'igw = aws.ec2.InternetGateway("igw", vpc_id=vpc.id,',
            f'    tags={{"Name": {_py_str(plan.project_name + "-igw")}}}, opts=opts)',
        ]

    lines.append("")
    for s in net.subnets:
        public = s.tier == SubnetTier.PUBLIC
        lines += [
            f"subnet_{s.resource_name} = aws.ec2.Subnet(",
            f"    {_py_str(s.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    cidr_block={_py_str(s.cidr)},",
            f"    availability_zone=azs.names[{s.availability_zone_index}],",
            f"    map_public_ip_on_launch={public},",
            f'    tags={{"Name": {_py_str(s.name)}, "Tier": {_py_str(s.tier.value)}}},',
            "    opts=opts,",
            ")",
        ]

    lines += ["", "# --- Security groups -----------------------------------------------------"]
    for sg in net.security_groups:
        ingress = "\n".join(_ingress_block(r) for r in sg.ingress)
        lines += [
            f"sg_{sg.resource_name} = aws.ec2.SecurityGroup(",
            f"    {_py_str(sg.resource_name)},",
            "    vpc_id=vpc.id,",
            f"    description={_py_str(sg.description or sg.name)},",
            "    ingress=[",
            ingress,
            "    ],",
            '    egress=[{"protocol": "-1", "from_port": 0, "to_port": 0, '
            '"cidr_blocks": ["0.0.0.0/0"]}],',
            f'    tags={{"Name": {_py_str(sg.name)}}},',
            "    opts=opts,",
            ")",
        ]

    # AMI lookups, one per distinct OS image.
    lines += ["", "# --- AMI lookups ---------------------------------------------------------"]
    image_keys = sorted({c.image_key for c in plan.compute})
    for key in image_keys:
        ref = target.image_reference(key)
        owners = ", ".join(_py_str(o) for o in ref.get("owners", []))
        name = _py_str(ref.get("name", "*"))
        var = terraform_safe_name(key)
        lines += [
            f"ami_{var} = aws.ec2.get_ami(",
            "    most_recent=True,",
            f"    owners=[{owners}],",
            f'    filters=[{{"name": "name", "values": [{name}]}},',
            '             {"name": "virtualization-type", "values": ["hvm"]}],',
            ")",
        ]

    # Instances.
    lines += ["", "# --- Instances -----------------------------------------------------------"]
    for c in plan.compute:
        ami_var = terraform_safe_name(c.image_key)
        subnet_res = subnet_of[c.vm_name]
        sg_res = sg_resource.get(c.security_group)
        sg_ref = f"sg_{sg_res}.id" if sg_res else "None"
        lines += [
            f"inst_{c.resource_name} = aws.ec2.Instance(",
            f"    {_py_str(c.resource_name)},",
            f"    instance_type={_py_str(c.instance_type)},",
            f"    ami=ami_{ami_var}.id,",
            f"    subnet_id=subnet_{subnet_res}.id,",
            f"    vpc_security_group_ids=[{sg_ref}],",
            f'    root_block_device={{"volume_size": {c.root_volume_gib}, "volume_type": "gp3"}},',
            f'    tags={{"Name": {_py_str(c.vm_name)}, "Tier": {_py_str(c.tier.value)}, '
            f'"Environment": {_py_str(c.environment.value)}}},',
            "    opts=opts,",
            ")",
        ]
        if c.external_id:
            # Brownfield: adopt the existing instance rather than recreate it.
            lines[-1] = (
                "    opts=pulumi.ResourceOptions(provider=provider, "
                f"import_={_py_str(c.external_id)}),"
            )
            lines.append(")")

    lines += [
        "",
        'pulumi.export("vpc_id", vpc.id)',
        'pulumi.export("instance_count", ' + str(plan.vm_count) + ")",
        "",
    ]
    return "\n".join(lines)


def _azure_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)
    sg_resource = {sg.name: sg.resource_name for sg in net.security_groups}

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (Azure)."""',
        "import pulumi",
        "import pulumi_azure as azure",
        "",
        "config = pulumi.Config()",
        'admin_username = config.get("adminUsername") or "azureuser"',
        'admin_password = config.get_secret("adminPassword") or "REPLACE_ME_Str0ng!Pass"',
        'admin_ssh_public_key = config.get("adminSshPublicKey") or "ssh-rsa REPLACE_ME"',
        f"location = {_py_str(plan.region)}",
        "",
        "rg = azure.core.ResourceGroup(",
        '    "rg",',
        f"    name={_py_str(plan.project_name + '-rg')},",
        "    location=location,",
        ")",
        "vnet = azure.network.VirtualNetwork(",
        '    "vnet",',
        "    resource_group_name=rg.name,",
        "    location=rg.location,",
        f"    address_spaces=[{_py_str(net.vpc_cidr)}],",
        ")",
    ]

    for s in net.subnets:
        lines += [
            f"subnet_{s.resource_name} = azure.network.Subnet(",
            f"    {_py_str(s.resource_name)},",
            "    resource_group_name=rg.name,",
            "    virtual_network_name=vnet.name,",
            f"    address_prefixes=[{_py_str(s.cidr)}],",
            ")",
        ]

    # NSGs with security rules.
    for sg in net.security_groups:
        rules = []
        for i, r in enumerate(sg.ingress):
            port = f"{r.from_port}" if r.from_port == r.to_port else f"{r.from_port}-{r.to_port}"
            src = r.cidr_blocks[0] if r.cidr_blocks else "*"
            rules.append(
                "        {"
                f'"name": {_py_str("rule-" + str(i))}, "priority": {100 + i * 10}, '
                '"direction": "Inbound", "access": "Allow", '
                f'"protocol": {_py_str(r.protocol.capitalize())}, '
                '"source_port_range": "*", '
                f'"destination_port_range": {_py_str(port)}, '
                f'"source_address_prefix": {_py_str(src)}, '
                '"destination_address_prefix": "*"},'
            )
        lines += [
            f"nsg_{sg.resource_name} = azure.network.NetworkSecurityGroup(",
            f"    {_py_str(sg.resource_name)},",
            "    resource_group_name=rg.name,",
            "    location=rg.location,",
            "    security_rules=[",
            *rules,
            "    ],",
            ")",
        ]

    for c in plan.compute:
        ref = target.image_reference(c.image_key)
        nic = f"nic_{c.resource_name}"
        subnet_res = subnet_of[c.vm_name]
        sg_res = sg_resource.get(c.security_group)
        is_windows = c.image_key.startswith("windows")
        public = c.subnet_tier == SubnetTier.PUBLIC
        if public:
            lines += [
                f"pip_{c.resource_name} = azure.network.PublicIp(",
                f"    {_py_str(c.resource_name)},",
                "    resource_group_name=rg.name, location=rg.location,",
                '    allocation_method="Static", sku="Standard",',
                ")",
            ]
        ip_cfg = (
            '        "name": "internal", '
            f'"subnet_id": subnet_{subnet_res}.id, '
            '"private_ip_address_allocation": "Dynamic"'
        )
        if public:
            ip_cfg += f', "public_ip_address_id": pip_{c.resource_name}.id'
        lines += [
            f"{nic} = azure.network.NetworkInterface(",
            f"    {_py_str(c.resource_name)},",
            "    resource_group_name=rg.name, location=rg.location,",
            "    ip_configurations=[{" + ip_cfg + "}],",
            ")",
        ]
        if sg_res:
            lines += [
                "azure.network.NetworkInterfaceSecurityGroupAssociation(",
                f"    {_py_str(c.resource_name)},",
                f"    network_interface_id={nic}.id,",
                f"    network_security_group_id=nsg_{sg_res}.id,",
                ")",
            ]
        vm_type = "WindowsVirtualMachine" if is_windows else "LinuxVirtualMachine"
        cred = (
            "    admin_password=admin_password,"
            if is_windows
            else "    admin_ssh_keys=[{\"username\": admin_username, "
                 '"public_key": admin_ssh_public_key}],'
        )
        lines += [
            f"inst_{c.resource_name} = azure.compute.{vm_type}(",
            f"    {_py_str(c.resource_name)},",
            "    resource_group_name=rg.name, location=rg.location,",
            f"    size={_py_str(c.instance_type)},",
            "    admin_username=admin_username,",
            cred,
            f"    network_interface_ids=[{nic}.id],",
            '    os_disk={"caching": "ReadWrite", "storage_account_type": "StandardSSD_LRS", '
            f'"disk_size_gb": {c.root_volume_gib}}},',
            "    source_image_reference={"
            f'"publisher": {_py_str(ref["publisher"])}, '
            f'"offer": {_py_str(ref["offer"])}, '
            f'"sku": {_py_str(ref["sku"])}, "version": "latest"}},',
            ")",
        ]

    lines += ["", 'pulumi.export("resource_group", rg.name)', ""]
    return "\n".join(lines)


def _gcp_main(plan: MigrationPlan, target: Target) -> str:
    net = plan.network
    subnet_of = _assign_subnets(plan)

    lines: List[str] = [
        f'"""Pulumi program generated by IaCTranslate — {plan.project_name} (GCP)."""',
        "import pulumi",
        "import pulumi_gcp as gcp",
        "",
        "config = pulumi.Config()",
        'project = config.get("gcpProject") or "REPLACE_ME_PROJECT_ID"',
        f"region = {_py_str(plan.region)}",
        f"zone = {_py_str(plan.region + '-a')}",
        "",
        "network = gcp.compute.Network(",
        '    "network",',
        "    auto_create_subnetworks=False,",
        "    project=project,",
        ")",
    ]

    for s in net.subnets:
        lines += [
            f"subnet_{s.resource_name} = gcp.compute.Subnetwork(",
            f"    {_py_str(s.resource_name)},",
            f"    ip_cidr_range={_py_str(s.cidr)},",
            "    region=region, network=network.id,",
            "    private_ip_google_access=True, project=project,",
            ")",
        ]

    # A firewall per security group, scoped to its tag.
    for sg in net.security_groups:
        tcp_ports = sorted({str(r.from_port) for r in sg.ingress if r.protocol.lower() == "tcp"})
        ports = ", ".join(_py_str(p) for p in tcp_ports) or '"22"'
        srcs = sorted({c for r in sg.ingress for c in r.cidr_blocks}) or ["0.0.0.0/0"]
        src_ranges = ", ".join(_py_str(c) for c in srcs)
        lines += [
            f"fw_{sg.resource_name} = gcp.compute.Firewall(",
            f"    {_py_str(sg.resource_name)},",
            "    network=network.name, project=project,",
            '    allows=[{"protocol": "tcp", "ports": [' + ports + "]}],",
            f"    source_ranges=[{src_ranges}],",
            f"    target_tags=[{_py_str(sg.name)}],",
            ")",
        ]

    for c in plan.compute:
        ref = target.image_reference(c.image_key)
        subnet_res = subnet_of[c.vm_name]
        public = c.subnet_tier == SubnetTier.PUBLIC
        access = "[{}]" if public else "[]"  # [{}] = one ephemeral external IP
        lines += [
            f"inst_{c.resource_name} = gcp.compute.Instance(",
            f"    {_py_str(c.resource_name)},",
            f"    machine_type={_py_str(c.instance_type)},",
            "    zone=zone, project=project,",
            f"    tags=[{_py_str(c.security_group)}],",
            '    boot_disk={"initialize_params": {"image": '
            f'{_py_str(ref["image"])}, "size": {c.root_volume_gib}, "type": "pd-balanced"}}}},',
            '    network_interfaces=[{"subnetwork": subnet_'
            f'{subnet_res}.id, "access_configs": {access}}}],',
            f'    labels={{"tier": {_py_str(c.tier.value)}, '
            f'"environment": {_py_str(c.environment.value)}}},',
            ")",
        ]

    lines += ["", 'pulumi.export("network", network.name)', ""]
    return "\n".join(lines)


# target -> (main-program builder, pip requirement, deploy note)
_CLOUD = {
    "aws": (_aws_main, "pulumi-aws>=6.0.0,<7.0.0", "AWS credentials (env vars or profile)"),
    "azure": (_azure_main, "pulumi-azure>=5.0.0,<6.0.0", "an Azure login (`az login`)"),
    "gcp": (
        _gcp_main, "pulumi-gcp>=7.0.0,<8.0.0",
        "`gcloud auth application-default login` and a project id "
        "(`pulumi config set gcpProject ...`)",
    ),
}


def _pulumi_yaml(plan: MigrationPlan) -> str:
    return (
        f"name: {terraform_safe_name(plan.project_name)}\n"
        "runtime:\n  name: python\n"
        f"description: IaCTranslate-generated migration of {plan.project_name} to {plan.target}.\n"
    )


def _readme(plan: MigrationPlan, deploy_note: str) -> str:
    return (
        f"# {plan.project_name} — Pulumi ({plan.target.upper()})\n\n"
        "Generated by IaCTranslate as an alternative to the Terraform output.\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "python -m venv venv && source venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        "pulumi stack init dev\n"
        "pulumi up\n"
        "```\n\n"
        f"OS images resolve automatically. Configure {deploy_note}.\n"
    )


def build_pulumi_files(plan: MigrationPlan, target: Target) -> Dict[str, str]:
    """Render the plan as a Pulumi Python project (AWS, Azure, or GCP)."""
    if target.name not in _CLOUD:
        raise RendererNotSupportedError(
            f"the Pulumi renderer does not support the '{target.name}' target"
        )
    main_fn, requirement, deploy_note = _CLOUD[target.name]
    return {
        "__main__.py": main_fn(plan, target),
        "Pulumi.yaml": _pulumi_yaml(plan),
        "requirements.txt": f"pulumi>=3.0.0,<4.0.0\n{requirement}\n",
        "README.md": _readme(plan, deploy_note),
    }
